### PR TITLE
Switch suffix for 10^9 downloads from 'G' to 'B'

### PR DESCRIPTION
**Pull request by sethmlarson**
On [behalf](https://pepy.tech/project/urllib3) [of](https://pepy.tech/project/six) [the](https://pepy.tech/project/python-dateutil) [billionaires](https://pepy.tech/project/botocore) [club](https://pepy.tech/project/pip) :moneybag: I think the download badges should read "Billion" rather than "Giga". The unit test names suggest this was considered.

Also switched from peta to quadrillion, probably won't have to worry about that though! :)

### CODE REVIEW

**Comment by psincraian** [comment]
Hi @sethmlarson,

I use the default System of Units: https://en.wikipedia.org/wiki/Metric_prefix

Also, another reason to use Giga vs. Billion is that billion can be [10^9 or 10^12](https://en.wikipedia.org/wiki/Billion) depending on the context.

If there is a vast demand, I can make this personalizable :-)

**Comment by sethmlarson** [comment]
Right, but one doesn't say "1 giga-download", you'd say 1 billion downloads. The "million million" definition is historical, both American and British English now recognize 10^9 as a billion.

**Comment by psincraian** [comment]
You are right. I don't say one giga-downloads, but I don't say one kilo-downloads either.

The problem is that at least for most of the European people, a Billion is equivalent to 10^12 https://en.wikipedia.org/wiki/Long_and_short_scales#Current_usage so the 'B' could lead to misinformation.

I still think that the best option is to use the SI prefix, and most users can understand k, M, G, B.

**Comment by sethmlarson** [comment]
No problem, thank you for providing this great service! :heart:

**Pull request closed without merging**
